config/routes.rb
Rails.application.routes.draw do
  resources :selected_projects
  resources :evaluations
  resources :project_assignments
  resources :revisions
  resources :reports, only: [:new, :create, :show, :edit, :update, :destroy]

  get 'revisions/observation'
  get 'revisions/validate' , to: 'revisions#validate'
  get 'static_pages/reports_by_project' , to: 'static_pages#reports_by_project',as: :static_pages_reports_by_project
  get 'static_pages/reports_by_project_id' , to: 'static_pages#reports_by_project_id',as: :stsatic_pages_reports_id_by_project

  get 'static_pages/home'
  get 'static_pages/creator'
  get 'static_pages/project'
  get 'static_pages/project_scores'
  get 'static_pages/privacy'
  get 'static_pages/evidence'
  post 'static_pages/savenew'
  get 'static_pages/save_selected', to: 'static_pages#save_selected',as: :static_pages_save_selected


  resources :projects
  match 'projects/:id/add_people', to: 'projects#add_people', as: :add_project_people , via: :all
  get 'projects/:id/anexos', to: 'projects#anexos', as: :add_anexo_people
  match 'projects/:id/documents_people', to: 'projects#add_documents_people', as: :add_documents_people, via: :all
  match 'projects/:id/information', to: 'projects#information', as: :project_information, via: :all
  match 'projects/:id/retribution', to: 'projects#retribution', as: :project_retribution, via: :all
  match 'projects/:id/evidence', to: 'projects#evidence', as: :project_evidence, via: :all
  match 'projects/:id/finish', to: 'projects#finish', as: :project_finish, via: :all
  match '/uploads/:class/:as/:id/:basename.:extension', to: 'projects#download', via: :all, as: :download_doc, :constraints => { :extension => /[^\/]+/ }
  resources :art_forms
  resources :categories
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    :registrations => "users/registrations",
    :confirmations => "users/confirmations",
    :passwords => "users/passwords"
  }

  resources :users
  resources :people

  root to: "projects#new"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  load_and_authorize_resource :class => User
  include ProjectsHelper

  def home
    @user = User.new
  end



  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def savenew
    @user = User.new(params.require(:user).permit(:first_name, :last_name, :second_last_name,:email,:account_active,  :person_id))
    @user.password = "123456"
    @user.role = params[:role]
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :home }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def creator
    @person = Person.where(:project_id => params[:project]).first
    @project = Project.where(:id=> params[:project]).first
  end

  def project
    @information = Information.where(:project_id => params[:project]).first
    @project = Project.where(:id=> params[:project]).first

  end

  def project_scores
    @test = []
    @projects = Project.where(:id => ProjectAssignment.select(:project_id).map(&:project_id))

    @projects.each do |p|
        @test.push({:score =>get_score(p.id).to_f,:pro => p})
    end
    @test.sort_by{|e| e[:pro]}

  end

  def save_selected
    @project = Project.find_by(id: params[:te])
    @project.selected = !@project.selected
    respond_to do |format|
      if @project.save
        format.html { redirect_to static_pages_project_scores_path}
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :home }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def privacy

  end

  def reports_by_project_id
    @reports = Report.where(project_id: params[:id])

  end


  def reports_by_project
    if current_user.role == :admin
      @reports = Report.where(project_id: params[:id])
    else
      @reports = Report.where(project_id: current_user.projects.first.blank? ? params[:id]:current_user.projects.first.id)
    end
    #@reports = Report.where(project_id: current_user.projects.first.blank? ? params[:id]:current_user.projects.first.id)

  end

  def evidence
    @information = Information.where(:project_id => params[:project]).first
    @project = Project.where(:id=> params[:project]).first

    @arts=@project.art_forms

      @arts.each do |a|
        @project.build_visual_evidence if @project.visual_evidence.blank? and VisualEvidence::ART_FORM_ID==a.id
        @project.build_dance_evidence if @project.dance_evidence.blank? and DanceEvidence::ART_FORM_ID==a.id
        @project.build_music_evidence if @project.music_evidence.blank? and MusicEvidence::ART_FORM_ID==a.id
        @project.build_theater_evidence if @project.theater_evidence.blank? and TheaterEvidence::ART_FORM_ID==a.id
        @project.build_film_evidence if @project.film_evidence.blank? and FilmEvidence::ART_FORM_ID==a.id
        @project.build_letter_evidence if @project.letter_evidence.blank? and LetterEvidence::ART_FORM_ID==a.id

      end


  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_dance_evidence_fields.html.erb
<div>
  <div class="col s12" style="border-top: 1px solid rgba(160,160,160,0.2); margin-top: 24px;">
    <span class="card-title" style="margin-top: 24px;">Evidencias Danza</span>
    <ul class="collection">

      <li class="collection-item avatar">
        <i class="material-icons circle">folder</i>
        <span class="title">Video de muestra</span>
        <div style="margin-top:16px">
          <%= f.text_field :video, disabled:true%>
          <a class='dropdown-button btn' href='#' data-activates='videodance'>Validar Video de muestra</a>
          <ul id='videodance' class='dropdown-content'>
            <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"video",:status=>"Valido", :model=>"dance_evidence")%>"data-confirm="¿Estás seguro?">Validar</a></li>
            <%if get_observation_id("video","dance_evidence") != ""%>
              <li><a href="<%=edit_revision_path(get_observation_id("video","dance_evidence"))%>">Editar observacion</a></li>
            <%else%>
              <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"video",:status=>"Invalido", :model=>"dance_evidence")%>">Agregar observaciones</a></li>
            <%end%>
          </ul>
          <%if get_status("video","dance_evidence") == "Invalido"%>
            <div class="input-field">
              <textarea class="materialize-textarea" disabled><%=get_observation("video","dance_evidence")%></textarea>
            </div>
          <%end%>
        </div>
        <div class="secondary-content">
          <%= get_status("video","dance_evidence") %>
        </div>
      </li>

      <li class="collection-item avatar">
        <i class="material-icons circle">folder</i>
        <span class="title">Sitio web</span>
        <div style="margin-top:16px">
          <%= f.text_field :web , disabled: true%>
          <a class='dropdown-button btn' href='#' data-activates='webdance'>Validar Sitio web</a>
          <ul id='webdance' class='dropdown-content'>
            <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"web",:status=>"Valido", :model=>"dance_evidence")%>"data-confirm="¿Estás seguro?">Validar</a></li>
            <%if get_observation_id("web","dance_evidence") != ""%>
              <li><a href="<%=edit_revision_path(get_observation_id("web","dance_evidence"))%>">Editar observacion</a></li>
            <%else%>
              <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"web",:status=>"Invalido", :model=>"dance_evidence")%>">Agregar observaciones</a></li>
            <%end%>
          </ul>
          <%if get_status("web","dance_evidence") == "Invalido"%>
            <div class="input-field">
              <textarea class="materialize-textarea" disabled><%=get_observation("web","dance_evidence")%></textarea>
            </div>
          <%end%>
        </div>
        <div class="secondary-content">
          <%= get_status("web","dance_evidence") %>
        </div>
      </li>
      <li class="collection-item avatar">
        <i class="material-icons circle">folder</i>
        <span class="title">Imágenes</span>
        <div style="margin-top:16px">
          <% f.object.image.each do |ob| %>
            <%= link_to 'Descargar', ob.url , :target=>"_blank", :class => 'waves-effect waves-light btn', :style => 'color:white;'%>
          <%end%>
          <a class='dropdown-button btn' href='#' data-activates='imagedance'>Validar Imágenes</a>
          <ul id='imagedance' class='dropdown-content'>
            <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"image",:status=>"Valido", :model=>"dance_evidence")%>"data-confirm="¿Estás seguro?">Validar</a></li>
            <%if get_observation_id("image","dance_evidence") != ""%>
              <li><a href="<%=edit_revision_path(get_observation_id("image","dance_evidence"))%>">Editar observacion</a></li>
            <%else%>
              <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"image",:status=>"Invalido", :model=>"dance_evidence")%>">Agregar observaciones</a></li>
            <%end%>
          </ul>
          <%if get_status("image","dance_evidence") == "Invalido"%>
            <div class="input-field">
              <textarea class="materialize-textarea" disabled><%=get_observation("image","dance_evidence")%></textarea>
            </div>
          <%end%>
        </div>
        <div class="secondary-content">
          <%= get_status("image","dance_evidence") %>
        </div>
      </li>

      <li class="collection-item avatar">
        <i class="material-icons circle">folder</i>
        <span class="title">Notas de prensa</span>
        <div style="margin-top:16px">
          <% f.object.note.each do |ob| %>
            <%= link_to 'Descargar', ob.url , :target=>"_blank", :class => 'waves-effect waves-light btn', :style => 'color:white;'%>
          <%end%>
          <a class='dropdown-button btn' href='#' data-activates='notedance'>Validar Notas de prensa</a>
          <ul id='notedance' class='dropdown-content'>
            <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"note",:status=>"Valido", :model=>"dance_evidence")%>"data-confirm="¿Estás seguro?">Validar</a></li>
            <%if get_observation_id("note","dance_evidence") != ""%>
              <li><a href="<%=edit_revision_path(get_observation_id("note","dance_evidence"))%>">Editar observacion</a></li>
            <%else%>
              <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"note",:status=>"Invalido", :model=>"dance_evidence")%>">Agregar observaciones</a></li>
            <%end%>
          </ul>
          <%if get_status("note","dance_evidence") == "Invalido"%>
            <div class="input-field">
              <textarea class="materialize-textarea" disabled><%=get_observation("note","dance_evidence")%></textarea>
            </div>
          <%end%>
        </div>
        <div class="secondary-content">
          <%= get_status("note","dance_evidence") %>
        </div>
      </li>


      <li class="collection-item avatar">
        <i class="material-icons circle">folder</i>
        <span class="title">Invitaciones, constancias y/o reconocimientos</span>
        <div style="margin-top:16px">
          <% f.object.document.each do |ob| %>
            <%= link_to 'Descargar', ob.url , :target=>"_blank", :class => 'waves-effect waves-light btn', :style => 'color:white;'%>
          <%end%>
          <a class='dropdown-button btn' href='#' data-activates='documentdance'>Validar Invitaciones, constancias y/o reconocimientos</a>
          <ul id='documentdance' class='dropdown-content'>
            <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"document",:status=>"Valido", :model=>"dance_evidence")%>"data-confirm="¿Estás seguro?">Validar</a></li>
            <%if get_observation_id("document","dance_evidence") != ""%>
              <li><a href="<%=edit_revision_path(get_observation_id("document","dance_evidence"))%>">Editar observacion</a></li>
            <%else%>
              <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"document",:status=>"Invalido", :model=>"dance_evidence")%>">Agregar observaciones</a></li>
            <%end%>
          </ul>
          <%if get_status("document","dance_evidence") == "Invalido"%>
            <div class="input-field">
              <textarea class="materialize-textarea" disabled><%=get_observation("document","dance_evidence")%></textarea>
            </div>
          <%end%>
        </div>
        <div class="secondary-content">
          <%= get_status("document","dance_evidence") %>
        </div>
      </li>




    </ul>
  </div>
</div>



<!--
<div >
  Danza
  <%= f.hidden_field :id %>
  <%= f.label 'Video de muestra' %>
  <%= f.text_field :video %>
  <%= f.label 'Sitio web' %>
  <%= f.text_field :web %>
  <div class="file-field input-field">
    <div class="btn">
      <span>
        Cargar
        <%= f.file_field :image, multiple: true  %>
      </span>
    </div>
    <div class="file-path-wrapper">
      <%= text_field_tag nil, f.object.images, class: 'file-path validate', placeholder: 'Imagenes' %>
    </div>
  </div>
  <div class="file-field input-field">
    <div class="btn">
      <span>
        Cargar
        <%= f.file_field :note, multiple: true  %>
      </span>
    </div>
    <div class="file-path-wrapper">
      <%= text_field_tag nil, f.object.notes, class: 'file-path validate', placeholder: 'Notas de prensa' %>
    </div>
  </div>
  <div class="file-field input-field">
    <div class="btn">
      <span>
        Cargar
        <%= f.file_field :document, multiple: true  %>
      </span>
    </div>
    <div class="file-path-wrapper">
      <%= text_field_tag nil, f.object.documents, class: 'file-path validate', placeholder: 'Invitaciones, constancias y/o reconocimientos' %>
    </div>
  </div>
</div>
-->

app/views/static_pages/_letter_evidence_fields.html.erb
<div>
  <div class="col s12" style="border-top: 1px solid rgba(160,160,160,0.2); margin-top: 24px;">
    <span class="card-title" style="margin-top: 24px;">Evidencias Letras</span>
    <ul class="collection">

           <li class="collection-item avatar">
        <i class="material-icons circle">folder</i>
        <span class="title">Sitio web</span>
        <div style="margin-top:16px">
          <%= f.text_field :web , disabled: true%>
          <a class='dropdown-button btn' href='#' data-activates='webletter'>Validar Sitio web</a>
          <ul id='webletter' class='dropdown-content'>
            <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"web",:status=>"Valido", :model=>"letter_evidence")%>"data-confirm="¿Estás seguro?">Validar</a></li>
            <%if get_observation_id("web","letter_evidence") != ""%>
              <li><a href="<%=edit_revision_path(get_observation_id("web","letter_evidence"))%>">Editar observacion</a></li>
            <%else%>
              <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"web",:status=>"Invalido", :model=>"letter_evidence")%>">Agregar observaciones</a></li>
            <%end%>
          </ul>
          <%if get_status("web","letter_evidence") == "Invalido"%>
            <div class="input-field">
              <textarea class="materialize-textarea" disabled><%=get_observation("web","letter_evidence")%></textarea>
            </div>
          <%end%>
        </div>
        <div class="secondary-content">
          <%= get_status("web","letter_evidence") %>
        </div>
      </li>



      <li class="collection-item avatar">
        <i class="material-icons circle">folder</i>
        <span class="title">Texto</span>
        <div style="margin-top:16px">
          <%unless f.object.work.url.nil?%>
            <%= link_to 'Descargar Texto',f.object.work.url , :target=>"_blank", :class => 'waves-effect waves-light btn', :style => 'color:white;'%>
          <%end%>
          <a class='dropdown-button btn' href='#' data-activates='work'>Validar Texto</a>
          <ul id='work' class='dropdown-content'>
            <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"work",:status=>"Valido", :model=>"letter_evidence")%>"data-confirm="¿Estás seguro?">Validar</a></li>
            <%if get_observation_id("work","letter_evidence") != ""%>
              <li><a href="<%=edit_revision_path(get_observation_id("work","letter_evidence"))%>">Editar observacion</a></li>
            <%else%>
              <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"work",:status=>"Invalido", :model=>"letter_evidence")%>">Agregar observaciones</a></li>
            <%end%>
          </ul>
          <%if get_status("work","letter_evidence") == "Invalido"%>
            <div class="input-field">
              <textarea class="materialize-textarea" disabled><%=get_observation("work","letter_evidence")%></textarea>
            </div>
          <%end%>
        </div>
        <div class="secondary-content">
          <%= get_status("work","letter_evidence") %>
        </div>
      </li>



      <li class="collection-item avatar">
        <i class="material-icons circle">folder</i>
        <span class="title">Portadas</span>
        <div style="margin-top:16px">
          <% f.object.cover.each do |ob| %>
             <%= link_to 'Descargar Portada', ob.url , :target=>"_blank", :class => 'waves-effect waves-light btn', :style => 'color:white;'%>
          <%end%>
          <a class='dropdown-button btn' href='#' data-activates='cover'>Validar Portadas</a>
          <ul id='cover' class='dropdown-content'>
            <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"cover",:status=>"Valido", :model=>"letter_evidence")%>"data-confirm="¿Estás seguro?">Validar</a></li>
            <%if get_observation_id("cover","letter_evidence") != ""%>
              <li><a href="<%=edit_revision_path(get_observation_id("cover","letter_evidence"))%>">Editar observacion</a></li>
            <%else%>
              <li><a href="<%=new_revision_path(:project_id => @project.id, :user_id=> @project.user.id,:field=>"cover",:status=>"Invalido", :model=>"letter_evidence")%>">Agregar observaciones</a></li>
            <%end%>
          </ul>
          <%if get_status("cover","letter_evidence") == "Invalido"%>
            <div class="input-field">
              <textarea class="materialize-textarea" disabled><%=get_observation("cover","letter_evidence")%></textarea>
            </div>
          <%end%>
        </div>
        <div class="secondary-content">
          <%= get_status("cover","letter_evidence") %>
        </div>
      </li>

    </ul>
  </div>
</div>





<!--


<div >
  Letras
  <%= f.hidden_field :id %>
  <%= f.label 'Sitio web' %>
  <%= f.text_field :web %>
  <div class="file-field input-field">
    <div class="btn">
      <span>
        Cargar
        <%= f.file_field :work %>
        <%= text_field_tag nil, f.object.work_identifier, class: 'file-path validate', placeholder: 'Texto' %>

      </span>
    </div>
    <div class="file-path-wrapper">
      <%= text_field_tag nil, f.object.work_identifier, class: 'file-path validate', placeholder: 'Texto' %>
    </div>
  </div>
  <div class="file-field input-field">
    <div class="btn">
      <span>
        Cargar
        <%= f.file_field :cover, multiple:true %>

      </span>
    </div>
    <div class="file-path-wrapper">
      <%= text_field_tag nil, f.object.covers, class: 'file-path validate', placeholder: 'Portadas' %>
    </div>
  </div>
</div>
-->

app/views/static_pages/creator.html.erb
<div class="nested-fields" >
  <span class="card-title">Información del participante</span>

  <div class="row">
    <div class="col s12 m4">
      <div class="input-field">
        <%= label_tag :first_name, 'Nombre' %>
       <%= text_field_tag 'first_name' ,@person.first_name , disabled: true%>
      </div>
    </div>
    <div class="col s12 m4">
      <div class="input-field">
        <%= text_field_tag :last_name, @person.last_name , disabled: true%>
        <%= label_tag :last_name, 'Apellido paterno' %>
      </div>
    </div>


    <div class="col s12 m4">
      <div class="input-field">
        <%= text_field_tag :second_last_name, @person.second_last_name, disabled: true %>
        <%= label_tag :second_last_name, 'Apellido materno' %>
      </div>
    </div>


    <div class="col s12" style='padding: 0'>
      <div class="input-field birthdate">
        <%= text_field_tag :birthdate, @person.birthdate, start_year: Date.today.year - 100  , disabled: true %>
        <%= label_tag :birthdate, 'Fecha de nacimiento' %>
      </div>
    </div>


    <div class="col s6 m3">
      <div class="input-field">
        <%= text_field_tag :home_phone_number, @person.home_phone_number, maxlength: '12' , disabled: true%>
        <%= label_tag :home_phone_number, 'Teléfono' %>
      </div>
    </div>


    <div class="col s6 m3">
      <div class="input-field">
        <%= text_field_tag :cellphone, @person.cellphone , maxlength: '12', disabled: true %>
        <%= label_tag :cellphone, 'Celular' %>
      </div>
    </div>


    <div class="col s12 m6">
      <div class="input-field">
        <%= text_field_tag :level_study,@person.level_study , disabled: true%>
        <%= label_tag :level_study, 'Grado maximo de estudios' %>
      </div>
    </div>

  </div>
  <div class="row">

    <!--div class="col s12 m4 l3">
      <div class="input-field">
        <%= text_field_tag :birthplace,@person.birthplace , disabled: true%>
        <%= label_tag :birthplace, 'Lugar de nacimiento' %>
      </div>
    </div-->
    <div class="col s12 m4 l3">
      <div class="input-field">
        <%= text_field_tag :state, @person.state, disabled: true %>
        <%= label_tag :state, 'Estado' %>
      </div>
    </div>
    <div class="col s12 m4 l3">
      <div class="input-field">
        <%= text_field_tag :city, @person.city, disabled: true %>
        <%= label_tag :city, 'Ciudad' %>
      </div>
    </div>
    <div class="col s12 m4 l3">
      <div class="input-field">
        <%= text_field_tag :nationality, @person.nationality , disabled: true%>
        <%= label_tag :nationality, 'Nacionalidad' %>
      </div>
    </div>
  </div>
  <%#= @project.fields_for :addresses do |a| %>
    <%#= render 'projects/address_fields', f: a %>
  <%# end %>
  <div class="nested-fields row">
    <%#= f.hidden_field :id %>
    <div class="col s6 m4">
      <div class="input-field">
        <%= label_tag  :street, 'Calle' %>
        <%= text_field_tag :street ,@person.addresses.first.street, disabled: true%>
      </div>
    </div>
    <div class="col s6 m2 l1">
      <div class="input-field">
        <%= label_tag  :internal_number,'# int' %>
        <%=text_field_tag :internal_number,@person.addresses.first.internal_number, disabled: true %>
      </div>
    </div>
    <div class="col s6 m2 l1">
      <div class="input-field">
        <%= label_tag  :external_number, '# ext' %>
        <%= text_field_tag :external_number ,@person.addresses.first.external_number, disabled: true%>
      </div>
    </div>
    <div class="col s6 m4">
      <div class="input-field">
        <%= label_tag  :colony, 'Colonia' %>
        <%= text_field_tag :colony ,@person.addresses.first.colony, disabled: true %>
      </div>
    </div>
    <div class="col s6 m3 l2">
      <div class="input-field">
        <%= label_tag  :zip,'C.P.' %>
        <%= text_field_tag :zip ,@person.addresses.first.zip, disabled: true%>
      </div>
    </div>
  </div>



</div>
<%= link_to 'Back', project_path(params[:project]) %>

app/views/static_pages/evidence.html.erb
<%#= form_for(@project, url: project_evidence_path ) do |f| %>
  <%#= render 'errors' %>
  <% @arts.each do |a| %>
    <%#= f.fields_for :visual_evidence  do |p| %>
      <%= render 'visual_evidence_fields', f: p %>
    <%# end if  VisualEvidence::ART_FORM_ID==a.id %>
    <%#= f.fields_for :dance_evidence  do |p| %>
      <%#= render 'dance_evidence_fields', f: p %>
    <%# end if  DanceEvidence::ART_FORM_ID==a.id %>
    <%#= f.fields_for :music_evidence  do |p| %>
      <%#= render 'music_evidence_fields', f: p %>
    <%# end if  MusicEvidence::ART_FORM_ID==a.id %>
    <%#= f.fields_for :theater_evidence  do |p| %>
      <%#= render 'theater_evidence_fields', f: p %>
    <%# end if  TheaterEvidence::ART_FORM_ID==a.id %>
    <%#= f.fields_for :film_evidence  do |p| %>
      <%#= render 'film_evidence_fields', f: p %>
    <%# end if  FilmEvidence::ART_FORM_ID==a.id %>
    <%#= f.fields_for :letter_evidence  do |p| %>
      <%#= render 'letter_evidence_fields', f: p %>
    <%# end if  LetterEvidence::ART_FORM_ID==a.id %>
  <% end %>
  <%#= f.submit 'Actualizar información', :class => 'btn waves-effect waves-light' %>
<#% end %>

app/views/static_pages/project_scores.html.erb
<table>
  <thead>
    <tr>
      <th>Folio</th>
      <th>Creador</th>
      <th>Categoría</th>
      <th>Nombre</th>
      <th colspan="3">Puntaje</th>
      <th>Seleccionado</th>
      <th>Reportes</th>


    </tr>
  </thead>

  <tbody>
    <%  @test.sort_by{|e| -e[:score]}.each_with_index do |project,i| %>
      <tr>
        <td><%= project[:pro].folio %></td>
        <td><%= project[:pro].user.first_name %></td>
        <td><%= project[:pro].category.name %></td>
        <td><%= Information.find_by_project_id(project[:pro].id).name%></td>
        <td><%= project[:score] %></td>
        <td><%= link_to 'Seleccionar', static_pages_save_selected_path(:te=> project[:pro].id),:id=>"nonz"+i.to_s , :class => 'btn waves-effect waves-light'%></td>

        <td>
          <p>
              <%= check_box_tag "check",true,project[:pro].selected,:id =>"nonz"+i.to_s %>
              <label for=<%="nonz"+ i.to_s%>></label>
          </p>
        </td>
        <td><%= link_to 'Reportes', static_pages_reports_by_project_path(id: project[:pro].id), :class => 'btn waves-effect waves-light'%></td>

        <!--<td><%#= link_to 'Show', project %></td>
        <td><%#= link_to 'Edit', edit_project_path(project) %></td>
        <td><%#= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>

  </tbody>
</table>

app/views/static_pages/reports_by_project_id.html.erb
<p id="notice"><%= notice %></p>

<h1>Reportes</h1>

<table>
  <thead>
  <tr>
    <th>Project</th>
    <th>Year</th>
    <th>Period</th>
    <th>Number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%if !@reports.blank?%>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.project.information.name %></td>
        <td><%= report.year %></td>
        <td><%= report.period %></td>
        <td><%= report.number %></td>
        <td><%= link_to 'Ver', report %></td>
        <td><%= link_to 'Editar', edit_report_path(report) %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

<% if current_user&.role==:creator %>
  <%=link_to 'Nuevo Reporte', new_report_path %>
<%end%>