config/routes.rb
Rails.application.routes.draw do
  resources :selected_projects
  resources :evaluations
  resources :project_assignments
  resources :revisions
  resources :reports, only: [:new, :create, :show, :edit, :update, :destroy]

  get 'revisions/observation'
  get 'revisions/validate' , to: 'revisions#validate'
  get 'static_pages/reports_by_project' , to: 'static_pages#reports_by_project',as: :static_pages_reports_by_project
  get 'static_pages/reports_by_project_id' , to: 'static_pages#reports_by_project_id',as: :stsatic_pages_reports_id_by_project

  get 'static_pages/home'
  get 'static_pages/creator'
  get 'static_pages/project'
  get 'static_pages/project_scores'
  get 'static_pages/privacy'
  get 'static_pages/evidence'
  post 'static_pages/savenew'
  get 'static_pages/save_selected', to: 'static_pages#save_selected',as: :static_pages_save_selected


  resources :projects
  match 'projects/:id/add_people', to: 'projects#add_people', as: :add_project_people , via: :all
  get 'projects/:id/anexos', to: 'projects#anexos', as: :add_anexo_people
  match 'projects/:id/documents_people', to: 'projects#add_documents_people', as: :add_documents_people, via: :all
  match 'projects/:id/information', to: 'projects#information', as: :project_information, via: :all
  match 'projects/:id/retribution', to: 'projects#retribution', as: :project_retribution, via: :all
  match 'projects/:id/evidence', to: 'projects#evidence', as: :project_evidence, via: :all
  match 'projects/:id/finish', to: 'projects#finish', as: :project_finish, via: :all
  match '/uploads/:class/:as/:id/:basename.:extension', to: 'projects#download', via: :all, as: :download_doc, :constraints => { :extension => /[^\/]+/ }
  resources :art_forms
  resources :categories
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    :registrations => "users/registrations",
    :confirmations => "users/confirmations",
    :passwords => "users/passwords"
  }

  resources :users
  resources :people

  root to: "projects#new"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :addresses
  belongs_to :project
  has_one :user
  accepts_nested_attributes_for :addresses
  has_one :person_document
  accepts_nested_attributes_for :person_document,allow_destroy: true
  validates_presence_of :first_name, :last_name, :second_last_name, :birthdate,  
      :state, :city, :nationality, :level_study, :birthdate, :addresses
  def birthdate=(new_status)
    if new_status.class==Date
      date=new_status
    else
      date=Date.parse new_status.values.join("-")
    end
    write_attribute :birthdate, date
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource param_method: :people_params

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @project=Project.find params[:project]
    @project.people.build
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :second_last_name, :birthdate, :home_phone_number, :cellphone, :birthplace, :state, :city, :nationality, :level_study, :birthdate, :address_id)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :person_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :person_last_name %>
  </div>

  <div class="field">
    <%= form.label :second_last_name %>
    <%= form.text_field :second_last_name, id: :person_second_last_name %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select :birthdate, id: :person_birthdate %>
  </div>

  <div class="field">
    <%= form.label :home_phone_number %>
    <%= form.text_field :home_phone_number, id: :person_home_phone_number %>
  </div>

  <div class="field">
    <%= form.label :cellphone %>
    <%= form.text_field :cellphone, id: :person_cellphone %>
  </div>

  <!--div class="field">
    <%#= form.label :birthplace %>
    <%#= form.text_field :birthplace, id: :person_birthplace %>
  </div-->

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :person_state %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :person_city %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality, id: :person_nationality %>
  </div>

  <div class="field">
    <%= form.label :level_study %>
    <%= form.text_field :level_study, id: :person_level_study %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.text_field :birthdate, id: :person_birthdate %>
  </div>

  <div class="field">
    <%= form.label :address_id %>
    <%= form.text_field :address_id, id: :person_address_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person_fields.html.erb
<div class="nested-fields" >
  <span class="card-title">Información del participante</span>
  <%= link_to_remove_association "Remover participante", f unless @project.single? %>
  <%= f.hidden_field :id %>
  <div class="row">
    <div class="col s12 m4">
      <div class="input-field">
        <%= f.text_field :first_name, id: :person_first_name %>
        <%= f.label :first_name, 'Nombre' %>
      </div>
    </div>
    <div class="col s12 m4">
      <div class="input-field">
        <%= f.text_field :last_name, id: :person_last_name %>
        <%= f.label :last_name, 'Apellido paterno' %>
      </div>
    </div>
    <div class="col s12 m4">
      <div class="input-field">
        <%= f.text_field :second_last_name, id: :person_second_last_name %>
        <%= f.label :second_last_name, 'Apellido materno' %>
      </div>
    </div>
    <div class="col s12" style='padding: 0'>
      <div class="input-field birthdate">
        <%= f.date_select :birthdate, id: :person_birthdate, start_year: Date.today.year - 100  %>
        <%= f.label :birthdate, 'Fecha de nacimiento' %>
      </div>
    </div>
    <div class="col s6 m3">
      <div class="input-field">
        <%= f.text_field :home_phone_number, id: :person_home_phone_number, maxlength: '12' %>
        <%= f.label :home_phone_number, 'Teléfono' %>
      </div>
    </div>
    <div class="col s6 m3">
      <div class="input-field">
        <%= f.text_field :cellphone, id: :person_cellphone , maxlength: '12' %>
        <%= f.label :cellphone, 'Celular' %>
      </div>
    </div>
    <div class="col s12 m6">
      <div class="input-field">
        <%= f.text_field :level_study, id: :person_level_study %>
        <%= f.label :level_study, 'Grado maximo de estudios' %>
      </div>
    </div>
  </div>
  <div class="row">
    <!--div class="col s12 m4 l3">
      <div class="input-field">
        <%= f.text_field :birthplace, id: :person_birthplace %>
        <%= f.label :birthplace, 'Lugar de nacimiento' %>
      </div>
    </div-->
    <div class="col s12 m4 l3">
      <div class="input-field">
        <%= f.text_field :state, id: :person_state %>
        <%= f.label :state, 'Estado' %>
      </div>
    </div>
    <div class="col s12 m4 l3">
      <div class="input-field">
        <%= f.text_field :city, id: :person_city %>
        <%= f.label :city, 'Ciudad' %>
      </div>
    </div>
    <div class="col s12 m4 l3">
      <div class="input-field">
        <%= f.text_field :nationality, id: :person_nationality %>
        <%= f.label :nationality, 'Nacionalidad' %>
      </div>
    </div>
  </div>
  <% f.object.addresses.build if f.object.addresses.empty? %>
  <%= f.fields_for :addresses do |a| %>
  <%= render 'projects/address_fields', f: a %>
  <% end %>
</div>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Second last name</th>
      <th>Birthdate</th>
      <th>Home phone number</th>
      <th>Cellphone</th>
      <th>Birthplace</th>
      <th>State</th>
      <th>City</th>
      <th>Nationality</th>
      <th>Level study</th>
      <th>Birthdate</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.second_last_name %></td>
        <td><%= person.birthdate %></td>
        <td><%= person.home_phone_number %></td>
        <td><%= person.cellphone %></td>
        <td><%= person.birthplace %></td>
        <td><%= person.state %></td>
        <td><%= person.city %></td>
        <td><%= person.nationality %></td>
        <td><%= person.level_study %></td>
        <td><%= person.birthdate %></td>
        <td><%= person.address %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<%= render 'form', person: @person %>

<%= link_to 'Back', edit_project_path(params[:project]) %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Second last name:</strong>
  <%= @person.second_last_name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @person.birthdate %>
</p>

<p>
  <strong>Home phone number:</strong>
  <%= @person.home_phone_number %>
</p>

<p>
  <strong>Cellphone:</strong>
  <%= @person.cellphone %>
</p>

<!--p>
  <strong>Birthplace:</strong>
  <%= @person.birthplace %>
</p-->

<p>
  <strong>State:</strong>
  <%= @person.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @person.city %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @person.nationality %>
</p>

<p>
  <strong>Level study:</strong>
  <%= @person.level_study %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @person.birthdate %>
</p>

<p>
  <strong>Address:</strong>
  <%= @person.address %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>