config/routes.rb
Rails.application.routes.draw do
  resources :selected_projects
  resources :evaluations
  resources :project_assignments
  resources :revisions
  resources :reports, only: [:new, :create, :show, :edit, :update, :destroy]

  get 'revisions/observation'
  get 'revisions/validate' , to: 'revisions#validate'
  get 'static_pages/reports_by_project' , to: 'static_pages#reports_by_project',as: :static_pages_reports_by_project
  get 'static_pages/reports_by_project_id' , to: 'static_pages#reports_by_project_id',as: :stsatic_pages_reports_id_by_project

  get 'static_pages/home'
  get 'static_pages/creator'
  get 'static_pages/project'
  get 'static_pages/project_scores'
  get 'static_pages/privacy'
  get 'static_pages/evidence'
  post 'static_pages/savenew'
  get 'static_pages/save_selected', to: 'static_pages#save_selected',as: :static_pages_save_selected


  resources :projects
  match 'projects/:id/add_people', to: 'projects#add_people', as: :add_project_people , via: :all
  get 'projects/:id/anexos', to: 'projects#anexos', as: :add_anexo_people
  match 'projects/:id/documents_people', to: 'projects#add_documents_people', as: :add_documents_people, via: :all
  match 'projects/:id/information', to: 'projects#information', as: :project_information, via: :all
  match 'projects/:id/retribution', to: 'projects#retribution', as: :project_retribution, via: :all
  match 'projects/:id/evidence', to: 'projects#evidence', as: :project_evidence, via: :all
  match 'projects/:id/finish', to: 'projects#finish', as: :project_finish, via: :all
  match '/uploads/:class/:as/:id/:basename.:extension', to: 'projects#download', via: :all, as: :download_doc, :constraints => { :extension => /[^\/]+/ }
  resources :art_forms
  resources :categories
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    :registrations => "users/registrations",
    :confirmations => "users/confirmations",
    :passwords => "users/passwords"
  }

  resources :users
  resources :people

  root to: "projects#new"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  def self.options_array
    all.order(:name).map{|c| [c.name,c.id,{'data-single'=> c.single}] }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :active)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name  %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :category_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.active %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @category.active %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>