config/routes.rb
Rails.application.routes.draw do
  resources :selected_projects
  resources :evaluations
  resources :project_assignments
  resources :revisions
  resources :reports, only: [:new, :create, :show, :edit, :update, :destroy]

  get 'revisions/observation'
  get 'revisions/validate' , to: 'revisions#validate'
  get 'static_pages/reports_by_project' , to: 'static_pages#reports_by_project',as: :static_pages_reports_by_project
  get 'static_pages/reports_by_project_id' , to: 'static_pages#reports_by_project_id',as: :stsatic_pages_reports_id_by_project

  get 'static_pages/home'
  get 'static_pages/creator'
  get 'static_pages/project'
  get 'static_pages/project_scores'
  get 'static_pages/privacy'
  get 'static_pages/evidence'
  post 'static_pages/savenew'
  get 'static_pages/save_selected', to: 'static_pages#save_selected',as: :static_pages_save_selected


  resources :projects
  match 'projects/:id/add_people', to: 'projects#add_people', as: :add_project_people , via: :all
  get 'projects/:id/anexos', to: 'projects#anexos', as: :add_anexo_people
  match 'projects/:id/documents_people', to: 'projects#add_documents_people', as: :add_documents_people, via: :all
  match 'projects/:id/information', to: 'projects#information', as: :project_information, via: :all
  match 'projects/:id/retribution', to: 'projects#retribution', as: :project_retribution, via: :all
  match 'projects/:id/evidence', to: 'projects#evidence', as: :project_evidence, via: :all
  match 'projects/:id/finish', to: 'projects#finish', as: :project_finish, via: :all
  match '/uploads/:class/:as/:id/:basename.:extension', to: 'projects#download', via: :all, as: :download_doc, :constraints => { :extension => /[^\/]+/ }
  resources :art_forms
  resources :categories
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    :registrations => "users/registrations",
    :confirmations => "users/confirmations",
    :passwords => "users/passwords"
  }

  resources :users
  resources :people

  root to: "projects#new"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_creator_navigation.html.erb
<div class="col s12">
 <ul class="pagination">
  <li class="waves-effect <%= @proy_ready %> <%= @anexo_ready %> <%= url_for(:only_path => true) == nav_project ? "btn" : "" %>">
    <%= link_to nav_project do %>
    1.Registro
    <% end %>
  </li>
  <li class="waves-effect <%= @part_ready %> <%= @anexo_ready %> <%= url_for(:only_path => true) == nav_participant ? "btn" : "" %>" >
    <%= link_to nav_participant do %>
    2.Participantes
    <% end %>
  </li>
  <li class="waves-effect <%= @anexo_ready %> <%= url_for(:only_path => true) == nav_anexo ? "btn" : "" %>" >
    <%= link_to nav_anexo do %>
    3.Anexos
    <% end %>
  </li>
  <li class="waves-effect <%= @doc_ready %> <%= url_for(:only_path => true) == nav_documents ? "btn" : "" %>" >
    <%= link_to nav_documents do %>
    4.Documentos
    <% end %>
  </li>
  <li class="waves-effect <%= @info_ready %> <%= url_for(:only_path => true) == nav_information ? "btn" : "" %>" >
    <%= link_to nav_information do %>
    5.Proyecto
    <% end %>
  </li>
  <li class="waves-effect <%= @retri_ready %> <%= url_for(:only_path => true) == nav_retribution ? "btn" : "" %>" >
    <%= link_to nav_retribution do %>
    6.Retribución
    <% end %>
  </li>
  <li class="waves-effect <%= @evi_ready %> <%= url_for(:only_path => true) == nav_evidence ? "btn" : "" %>">
    <%= link_to nav_evidence do %>
    7.Evidencias
    <% end %>
  </li>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fomac</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <% flash.each do |message_type, message| %>
  <%= javascript_tag "$(document).ready(function(){ Materialize.toast('#{message}' )})" %>
  <% end %>
  <style>
  a:visited {
    color: #FFF;
  }
  a:hover {
    background-color: #E0E0E0;
  }
  p.flow-text{
    line-height: 105%
  }
</style>
</head>

<body>
  <header>
    <div class="background-header">
      <div class="header-container">
        <div class="row">
          <div class="col s12 m12 l6 hide-on-med-and-down center margin-top-sm">
            <a href="http://prueba.icm.gob.mx/">
              <%= image_tag "logo.jpg", class: 'responsive-img' %>
            </a>
          </div>
          <div class="col s12 m12 l6 hide-on-large-only left margin-top-sm">
            <%= image_tag "logo.jpg" %>
          </div>
          <div class="col s12 m12 l6 hide-on-med-and-down">
            <div class="row no-bottom-margin margin-top-sm">
              <div class="row no-bottom-margin font-size-xsm">
                <div class="col s4 offset-s5 m4 offset-m5 l4 offset-l5 center">
                  Síguenos
                </div>
              </div>
              <div class="col s4 offset-s5 m4 offset-m5 l4 offset-l5 center">
                <div class="col s3 m3 l3 no-padding"><a href="https://www.facebook.com/ICMchihuahua">
                  <%= image_tag "buttons/facebook_button.jpg" %>
                </a></div>
                <div class="col s3 m3 l3 no-padding"><a href="https://www.youtube.com/user/AudiovisualesICM">
                  <%= image_tag "buttons/youtube_button.jpg" %>
                </a></div>
                <div class="col s3 m3 l3 no-padding"><a href="">
                  <%= image_tag "buttons/twitter_button.jpg" %>
                </a></div>
                <div class="col s3 m3 l3 no-padding"><a href="">
                  <%= image_tag "buttons/instagram_button.jpg" %>
                </a></div>
              </div>
            </div>
            <div class="row no-bottom-margin">
              <div class="col s5 offset-s5 m5 offset-m5 l5 offset-l5">
                <form role="search" method="get" id="searchform" action="http://icm.webxaa.com/">
                  <div class="col s9 m9 l9 no-padding">
                    <input type="hidden" name="sentance" value="1">
                    <input id="s" name="s" type="text" class="validate">
                  </div>
                  <div class="col s3 m3 l3 padding-fix-search-button">
                    <input id="searchsubmit" src="<%= image_path  "buttons/search_button.jpg"  %>" type="image">
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row no-bottom-margin">
      <nav class="grey darken-2">
        <div class="custom-container">
          <div class="nav-wrapper">
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class=" center hide-on-med-and-down">
              <li><a href="http://prueba.icm.gob.mx/">INICIO</a></li>
              <li><a href="http://prueba.icm.gob.mx/?page_id=46">CARTELERA</a></li>
              <li><a class='dropdown-button' data-activates='info' href="http://prueba.icm.gob.mx/?page_id=130">¿QUIENES SOMOS?</a></li>
              <li><ul id='info' class='dropdown-content grey darken-2'>
                <li><a class="white-text" href="http://prueba.icm.gob.mx/?page_id=165">TRANSPARENCIA</a></li>
                <li class="divider"></li>
                <li><a class="white-text" href="http://prueba.icm.gob.mx/?page_id=181">AVISO DE PRIVACIDAD</a></li>
              </ul>
            </li>
            <li><a href="http://prueba.icm.gob.mx/?page_id=132">DIRECTORIO</a></li>
            <li><a class='dropdown-button' data-activates='areas' href="http://prueba.icm.gob.mx/?page_id=82">NUESTRAS ÁREAS</a></li>
            <li><ul id='areas' class='dropdown-content grey darken-2'>
              <li><a class="white-text" href="http://prueba.icm.gob.mx/?page_id=89">MUSEO SEBASTIAN</a></li>
              <li class="divider"></li>
              <li><a class="white-text" href="http://prueba.icm.gob.mx/?page_id=103">MEDIATECA</a></li>
              <li class="divider"></li>
              <li><a class="white-text" href="http://prueba.icm.gob.mx/?page_id=121">TEATRO DE LA CIUDAD</a></li>
              <li class="divider"></li>
              <li><a class="white-text" href="http://prueba.icm.gob.mx/?page_id=125">CDC</a></li>
              <li class="divider"></li>
              <li><a class="white-text" href="http://prueba.icm.gob.mx/?page_id=127">CONSERVATORIO</a></li>
            </ul>
          </li>
          <li><a href="http://prueba.icm.gob.mx/?page_id=71">PRENSA</a></li>
          <li><a href="http://prueba.icm.gob.mx/?page_id=80">NUESTROS PRODUCTOS</a></li>
          <li><a href="http://prueba.icm.gob.mx/?page_id=53">CONTACTO</a></li>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><a href="">INICIO</a></li>
          <li><a href="http://prueba.icm.gob.mx/?page_id=46">CARTELERA</a></li>
          <li><a href="http://prueba.icm.gob.mx/?page_id=130">¿QUIENES SOMOS?</a></li>
          <li><a href="http://prueba.icm.gob.mx/?page_id=132">DIRECTORIO</a></li>
          <li><a href="http://prueba.icm.gob.mx/?page_id=82">NUESTRAS ÁREAS</a></li>
          <li><ul>
            <li><a href="http://prueba.icm.gob.mx/?page_id=89">MUSEO SEBASTIAN</a></li>
            <li><a href="http://prueba.icm.gob.mx/?page_id=103">MEDIATECA</a></li>
            <li><a href="http://prueba.icm.gob.mx/?page_id=121">TEATRO DE LA CIUDAD</a></li>
            <li><a href="http://prueba.icm.gob.mx/?page_id=125">CDC</a></li>
            <li><a href="http://prueba.icm.gob.mx/?page_id=127">CONSERVATORIO</a></li>
          </ul></li>
          <li><a href="http://prueba.icm.gob.mx/?page_id=71">PRENSA</a></li>
          <li><a href="http://prueba.icm.gob.mx/?page_id=80">NUESTROS PRODUCTOS</a></li>
          <li><a href="http://prueba.icm.gob.mx/?page_id=53">CONTACTO</a></li>
        </ul>


      </div>
    </div>
  </nav>
</div>
</header>
<section id="main-content">
  <section class="grey lighten-5 login-form">
    <div class="container">
      <div class="row">
        <div class="col s12 m12 l12 z-depth-5 card col-center animated bounceInRight">
          <div class="card-content">
            <%= yield %>
          </div>
        </div>
        <%= render 'layouts/creator_navigation' if current_user&.role==:creator and !@project&.finish? and (@project.blank? ? false: !@project.selected) %>
      </div>
    </div>
    <div class="fixed-action-btn">
      <%#= link_to(t(:proyect),project_path(@project.id), class: 'btn waves-effect waves-light red lighten-1', :style=>"color:white") if user_signed_in? && current_user&.role==:creator %>
      <%if current_user&.role==:admin or current_user&.role==:judge%>
      <%= link_to(t(:proyectos),projects_path, class: 'btn waves-effect waves-light blue', :style=>"color:white!important") if user_signed_in?  %>
      <% end %>
      <%if current_user&.role==:admin%>
      <%= link_to(t(:usuarios),users_path, class: 'btn waves-effect waves-light blue', :style=>"color:white!important") if user_signed_in?  %>
      <% end %>
      <%= link_to('Cerrar sesión',destroy_user_session_path, method: :delete, class: 'btn waves-effect waves-light red lighten-1', :style=>"color:white!important") if user_signed_in?  %>

    </div>
  </section>
  <footer class="page-footer white ">
    <div class="col s12 m12 l12 center">
      <%= image_tag "placeholders/logo-chihuahua.jpg" , class: 'responsive-img' %><br>
      <%= link_to("Aviso de Privacidad",static_pages_privacy_path)%>
    </div>
  </footer>
</section>